### ISSUE TITLE
Dolphin's Space information is not aligned with Zoom slider

### ISSUE THREAD

**Issue by trmdi** [yeyushengfan258/DeepinV20-kde#3]
Dolphin: 20.12

See my screenshot with the Deepin theme:
![image](https://user-images.githubusercontent.com/11857205/103297290-955e5000-4a2a-11eb-942b-12e06b56b41e.png)

Compare with the one in your `Readme.md`:
![image](https://user-images.githubusercontent.com/11857205/103297727-7ca26a00-4a2b-11eb-81e2-4b749bc83070.png)
and with Breeze:
![image](https://user-images.githubusercontent.com/11857205/103297943-e7ec3c00-4a2b-11eb-8615-da363ea47b3a.png)

Is this a theme bug or Kvantum bug? I also see it happens with KvMojave.

CC: @tsujan

**Comment by tsujan** [comment]
There's no bug.

In Kvantum, the external text of a progressbar is put above it by default (like GTK and unlike Breeze). Only if there's no enough space above the progressbar, the text will be placed in front of it.

**Comment by trmdi** [comment]
> There's no bug.

Then how can I move the text to the right of the bar like Breeze? Is this the design of the theme?

**Comment by tsujan** [comment]
>  Is this the design of the theme?

Yes, but not only that. The limited space that's given to the widget by Dolphin's code (incorrect but tolerable) as well as the font and its size also play their roles.

In an ideal world, the space that's given to a widget is, at least, equal to the space that's needed by the widget. Many KDE codes are far from ideal.

**Comment by yeyushengfan258** [comment]
As far as I know, only integrated graphics cards line up side by side. With a separate graphics card, it will stagger.

**Comment by trmdi** [comment]
> As far as I know, only integrated graphics cards line up side by side. With a separate graphics card, it will stagger.

I'm using the integrated one. So, who is responsible for this?

**Comment by tsujan** [comment]
I'm afraid there are misunderstandings here. First, it had nothing to do with the graphic card. Second, the slider and progressbar are horizontally aligned in ALL screenshots (progressbar = bar + text).

**Comment by yeyushengfan258** [comment]
I have misunderstood this problem and I do not know how to deal with it. I have the same problem using vinceliuice's topic.

**Comment by tsujan** [comment]
> I have misunderstood this problem

That's the misunderstanding. There is no problem to solve. → https://github.com/yeyushengfan258/DeepinV20-white-kde/issues/3#issuecomment-752145962

**Comment by yeyushengfan258** [comment]
> > I have misunderstood this problem
> 
> That's the misunderstanding. There is no problem to solve. → [#3 (comment)](https://github.com/yeyushengfan258/DeepinV20-white-kde/issues/3#issuecomment-752145962)

I see. This is also a problem That I have been trying to solve for me. It is a bit confusing.
Thank you for your explanation, which is also helpful to me.

**Comment by trmdi** [comment]
So, is there any way to force the text to be side by side with the bar? I think that is what we want here.

**Comment by yeyushengfan258** [comment]
> So, is there any way to force the text to be side by side with the bar? I think that is what we want here.

I don't know right now. Maybe I'll figure it out someday

**Comment by tsujan** [comment]
> So, is there any way to force the text to be side by side with the bar?

Let me explain it with more details, hoping that everything becomes crystal clear:

Unlike Breeze, Kvantum doesn't put the text in front of the bar because that's a bad design (sorry, I don't have time to explain why but it's terrible). Instead, Kvantum puts the text above the bar (as GTK does).

Now, Kvantum has many workarounds for bad styling codes. If a bad code doesn't provide the space a widget asks for (and that's one aspect of bad codes), Kvantum will try to compensate for it as far as possible. In this case, Dolphin's "progressbar" is the problem. Kvantum puts the text in front of the bar *only when there's not enough space above it.* I emphasize that **if the code was correct, there should always be enough space.**

In the first screenshot, the bar is so thin that there's no need to a compensation. If you want to trigger the faulty behavior of Dolphin's "progressbar" intentionally, give the progressbar a small but invisible frame in your themes (I think 1 or 2 pix should be enough).

**Comment by trmdi** [comment]
I found that the caption above the progressbar looks ok, but it seems they are not perfectly aligned inside the red rectangle?
Is there any way to move e.g. the caption about -1px to the top and the progressbar about -3px to the top?
![image](https://user-images.githubusercontent.com/11857205/103920650-21b3f580-5144-11eb-97db-bcca06a9470e.png)

![image](https://user-images.githubusercontent.com/11857205/103924528-bb7da180-5148-11eb-9900-46a699a3d735.png)

**Comment by tsujan** [comment]
> but it seems they are not perfectly aligned

They're perfectly aligned. The bar is exactly at the bottom of the widget's rectangle and the text is exactly at its top. There's a hard-coded 3-px spacing between the text and bar rectangles.

Qt (correctly) considers the maximum character height of the used font when drawing texts; that's why you may think that the text isn't aligned. Check your screenshot (I didn't have time to remove all of the line you'd drawn):

![aligned](https://user-images.githubusercontent.com/981076/104053546-b5e39280-5200-11eb-9ee7-adfe4e026a7d.png)

**Comment by trmdi** [comment]
> They're perfectly aligned.

Maybe I didn't describe it clearly. But I still feel something is not aligned.

![image](https://user-images.githubusercontent.com/11857205/104081818-d85ac780-5263-11eb-9cb1-cd63b3bafd31.png)

How to move the zoom slider a bit lower?

**Comment by tsujan** [comment]
> But I still feel something is not aligned.

The alignment is exact mathematically. I explained it above why you can't rely on your feelings when there is a text (→ max. char. height  in the font).

**Comment by trmdi** [comment]
> > But I still feel something is not aligned.
> 
> The alignment is exact mathematically. I explained it above why you can't rely on your feelings when there is a text (→ max. char. height in the font).

Ok, thank you very much.

**Comment by tsujan** [comment]
One more thing:

You would have the same feeling about the text at the left if it was at the right. I moved it to the right by editing your last screenshot:

![feeling](https://user-images.githubusercontent.com/981076/104088288-ec5df380-527a-11eb-9f90-cb432d221493.png)
